# Generated by Django 5.0.14 on 2025-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='chat_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
