# Generated by Django 5.0.14 on 2025-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0002_project_ai_response_project_chat_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fon_turu',
            field=models.CharField(blank=True, help_text='Örn. TÜBİTAK 1001, 1002 vb.', max_length=50, null=True, verbose_name='Fon Türü'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_months',
            field=models.IntegerField(default=12, help_text='Fon türüne göre önerilen proje süresi', verbose_name='Proje Süresi (Ay)'),
        ),
    ]
