# Generated by Django 5.0.14 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0003_project_fon_turu_alter_project_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_suresi', models.IntegerField(help_text='Bu fonun önerilen ya da azami süresi (ay olarak)', verbose_name='Varsayılan Süre (Ay)')),
            ],
        ),
    ]
