# Generated by Django 5.0.14 on 2025-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0004_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
