# Generated by Django 5.0.14 on 2025-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0005_alter_fund_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDuration',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('default_suresi', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'project_planning_fund',
                'managed': False,
            },
        ),
    ]
