# Generated by Django 5.0.14 on 2025-05-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0006_fundduration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fund",
        ),
        migrations.AlterModelOptions(
            name="fundduration",
            options={
                "managed": False,
                "ordering": ["kod"],
                "verbose_name": "Fon Süresi",
                "verbose_name_plural": "Fon Süreleri",
            },
        ),
        migrations.AlterModelTable(
            name="fundduration",
            table="chat_fon",
        ),
    ]
