# Generated by Django 5.0.14 on 2025-05-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_title_alter_chatsession_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='ai_model',
            field=models.CharField(choices=[('openai', 'OpenAI GPT-3.5'), ('lstm', 'Custom LSTM Model')], default='openai', max_length=20),
        ),
    ]
