# Generated by Django 5.0.14 on 2025-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_model',
            field=models.CharField(choices=[('custom_lstm', 'Custom LSTM Model'), ('deepseek', 'DeepSeek Chat API')], default='deepseek', max_length=20),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
