# Generated by Django 5.0.14 on 2025-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_is_active_alter_chatsession_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_model',
            field=models.CharField(choices=[('openai', 'OpenAI GPT-3.5'), ('lstm', 'Custom LSTM Model')], default='openai', max_length=50),
        ),
    ]
