# Generated by Django 5.0.14 on 2025-05-18 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatsession_title_alter_chatsession_ai_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(default=django.utils.timezone.now)),
                ("tahmin_sayisi", models.IntegerField(default=0)),
                ("ortalama_puan", models.FloatField(default=0.0)),
                ("basarili_tahmin", models.IntegerField(default=0)),
                ("egitim_sayisi", models.IntegerField(default=0)),
                ("egitim_suresi", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Agent Performans",
                "verbose_name_plural": "Agent Performans Metrikleri",
                "ordering": ["-tarih"],
            },
        ),
        migrations.CreateModel(
            name="Fon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20)),
                ("tur", models.CharField(max_length=100)),
                ("ay_suresi", models.IntegerField()),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fon",
                "verbose_name_plural": "Fonlar",
                "ordering": ["kod"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AiPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("ay_suresi", models.IntegerField()),
                ("plan_metni", models.TextField()),
                ("meta_data", models.TextField(blank=True, null=True)),
                ("feedback_score", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_planlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planlar",
                        to="chat.fon",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Plan",
                "verbose_name_plural": "AI Planlar",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_tipi",
                    models.CharField(
                        choices=[
                            ("tahmin", "Tahmin"),
                            ("egitim", "Eğitim"),
                            ("geri_bildirim", "Geri Bildirim"),
                            ("pdf", "PDF Oluşturma"),
                            ("hata", "Hata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detay", models.TextField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loglar",
                        to="chat.aiplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Log",
                "verbose_name_plural": "Agent Loglar",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="related_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="chat.aiplan",
            ),
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puan", models.IntegerField()),
                ("yorum", models.TextField(blank=True, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chat.aiplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Geri Bildirimi",
                "verbose_name_plural": "Kullanıcı Geri Bildirimleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
