# Generated by Django 5.0.14 on 2025-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_agentperformance_fon_chatmessage_metadata_aiplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="olusturma_tarihi",
            field=models.CharField(max_length=30),
        ),
    ]
