# Generated by Django 5.0.14 on 2025-05-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatmessage_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="chat.aiplan",
            ),
        ),
    ]
