# Generated by Django 5.0.14 on 2025-05-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatmessage_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="chat.aiplan",
            ),
        ),
    ]
